// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhlnoxglrujikjztwdrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobG5veGdscnVqaWtqenR3ZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTMzNTIsImV4cCI6MjA2MTg4OTM1Mn0.zZPaZzTSMpzam1cMn5nT1Oj8xqXAeMg4qWI6P08st44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);